### ISSUE TITLE
IngestRemap - Select most recent harvest data

### ISSUE THREAD

**Issue by moltude** [dpla/ingestion3#203]
With the implementation of #200 and #202 the `IngestRemap` entry needs to be able to find and select the most recent harvest data output to provide as the source data for mapping, Currently, this invocation relies upon a fixed path and deleting previous run data. This code should look within the `./harvest/` folder and identify the most recent folder using the date time in the folder name (`20180906_131309-pa-OriginalRecord.avro`)

Since harvests are the only process that currently uses this timestamped folder name, the other processes do not need to search for the most recent data for their input. They will continue to use the hard-coded paths.

https://github.com/dpla/ingestion3/blob/38c8b10501c09f429a339a298eda80c4eed50e70/src/main/scala/dpla/ingestion3/entries/ingest/IngestRemap.scala#L33-L38

https://github.com/dpla/ingestion3/blob/38c8b10501c09f429a339a298eda80c4eed50e70/src/main/scala/dpla/ingestion3/entries/ingest/IngestRemap.scala#L64-L73

**Comment by mdellabitta** [comment]
I think in the end, everything is meant to have timestamps.

**Comment by moltude** [comment]
Yes but I didn't want this to be a `fix-all` ticket, easy enough to just implement with harvest data for now.
